import type { ActivityItem } from "@/types";

export const mockActivities: ActivityItem[] = [
  {
    id: 1,
    mode: "Puzzle Game Mode",
    level: 22,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/bag-coins.svg",
  },
  {
    id: 2,
    mode: "Endless Game Mode",
    level: 6,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/chest.svg",
  },
  {
    id: 3,
    mode: "Adventure Game Mode",
    level: 10,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/coins-rocks.svg",
  },
  {
    id: 4,
    mode: "Daily Challenge Game Mode",
    level: 31,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/chest-2.svg",
  },
  {
    id: 5,
    mode: "Practice Game Mode",
    level: 12,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/chest-3.svg",
  },
  {
    id: 6,
    mode: "Challenge Game Mode",
    level: 41,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/chest-4.svg",
  },
  {
    id: 7,
    mode: "Timed Blitz Game Mode",
    level: 9,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/chest-5.svg",
  },
  {
    id: 8,
    mode: "Classic Game Mode",
    level: 16,
    groupSize: 10,
    participants: 12,
    coins: { gold: 50, red: 50 },
    earnings: 8,
    image: "/bag-coins-2.svg",
  },
];